name: Checkmarx One Scan
on:
  push:
    branches:
      - master
      - release-001
      - action-cx

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          project_name: sniper-zone/tftp
          cx_tenant: cx-cs-na-pspoc
          base_uri: https://deu.ast.checkmarx.net 
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
